# application-local.properties
spring.datasource.url=jdbc:mysql://localhost:3306/test
spring.datasource.username=root
spring.datasource.password=12345
spring.data.redis.host=localhost
spring.data.redis.port=6379
jwt.secret=YQI3rrGvzrAGqSzcuUJIT2z0xlCKHZYoCkYfQB32Ye8=
jwt.expiration=3600000
frontend.url=http://localhost:3000
admin.email=admin@gmail.com
admin.password=admin123
spring.mail.username=sbaasoufiane25@gmail.com
spring.mail.password=mjez wugc ilkn ztsa